<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/10/27
 * Time: 9:08
 */

namespace app\index\controller;

use app\admin\model\Attachment;
use app\index\model\Account;
use app\index\model\Country;
use app\index\model\Daytime;
use app\index\model\Donation;
use app\index\model\Topup;
use app\index\model\Location;
use app\index\model\Notice;
use app\index\model\Order;
use app\index\model\Orderitems;
use app\index\model\OrderStatus;
use app\index\model\Topic;
use app\index\model\Users;
use app\index\model\Withdrawal;
use app\user\model\User;
use think\Db;

class Member extends Home
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $user_id = session('user_id');
        $this->chk_login($user_id);
        $this->user_type = session('user_type');
        $this->assign('user_type', $this->user_type);
        $action = $this->request->action();
        if (session('is_partner') == 1 && $action != 'donate' && $action != 'edit_account' ) {
            $this->redirect('partner/index');
        }
    }

    public function index()
    {
        $user = Users::find($this->user_id);
        $time = time();
        $date2 = time_to_date($time, get_user_timezone(), 'Y-m-d H:i:s');
        $time2 = strtotime($date2);
        $this->assign('time_now', $time2);
        $this->assign('date_now', $date2);
        $time = strtotime('-30 minute');
        $user['md5'] = md5($user['password']);

        $app = config('app_android_apk');
        if ($app) {
            $apk = Attachment::find($app);
            $apk = '/public/'.$apk['path'];
        } else {
            $apk = '';
        }
        $this->assign('apk_downfile', $apk);

        if ($this->user_type == 2) {
            //老师
            $template = 'index_teacher';
            $topic = Topic::where('status', 1)->order('sort')->select();
            $this->assign('topic', $topic);
//            $learner_num = count(Orderitems::where(['teacher_id'=>$this->user_id])->where('order_status', 'in',[2])->group('user_id')->select());
//            $user['learner_num'] = $learner_num;

            $date = time_to_date(time(), get_user_timezone(), 'Y-m-d');
            $times = Daytime::where(['user_id' => $this->user_id, 'booked'=>0])->where("date",'egt', $date)->group('date')->select();
            $this->assign('teacher_times', $times);

            $list = Orderitems::alias('i')->field('i.*, username, location,country_id,native_language,english_level,descr,goals')
                ->join('cms_users u', 'user_id = u.id')
                ->where('teacher_id', $this->user_id)->where([ ['datetime','gt', $time], ['order_status','between',[1,3]] ] )->order('datetime asc')->select();
            $addstr = '_teacher';
        } else {
            $addstr = '';
            //学生
            $template = 'index_learner';

            $map = ['user_id' => $this->user_id];
            $teachers = Orderitems::get_teacher_list($map);
            $this->assign('teacher_list', $teachers);

            $list = Orderitems::alias('i')->field('i.*, username, location,country_id,native_language,english_level,descr,goals')
                ->join('cms_users u', 'teacher_id = u.id')
                ->where('user_id', $this->user_id)->where([['datetime','gt', $time], ['order_status','between',[1,3]] ] )->order('datetime asc ')->select();
        }
        $english_level = config('english_level');
        $native_language = config('native_language');
        $countrys = Country::get_list_col();
        $datetimes = [];
        foreach ($list as $k=>$row) {
//            $datetimes[] = ["datetime" => $row['datetime'],"booked"=>1,"date"=>$row['book_date'.$addstr],"time"=>$row['time_begin'.$addstr],"time_end"=>$row['time_end'.$addstr]];
            $temp = ['id'=>$row['id'], 'username' =>$row['username'], "datetime" => strtotime($row['book_date' . $addstr].' '.$row['time_begin' . $addstr]), "booked" => 1, "date" => $row['book_date' . $addstr], "time" => $row['time_begin' . $addstr], "time_end" => $row['time_end' . $addstr],'teacher_id'=>$row['teacher_id']];
            $temp['goals'] = $row['goals'];
            $temp['descr'] = $row['descr'];
            $temp['day'] = date('d', $temp['datetime']);
            $temp['month'] = date('M', $temp['datetime']);
            $temp['week'] = get_week($temp['datetime']);
            $temp['first'] = $native_language[$row['native_language']] ?? '';
            $temp['levels'] = $english_level[$row['english_level']] ?? '';
            $temp['location_name'] = $countrys[$row['country_id']]['country_name'] ?? '';
            $temp['location_ico'] = $countrys[$row['country_id']]['ico_file'] ?? '';

            $datetimes[] = $temp;
        }

        $this->assign('english_level', $english_level);
        $this->assign('class_list', $list);
        $this->assign('user_info', $user);
        $locaiton = get_user_timezone();
        $this->assign('location', $locaiton);
        $country = Country::cache(true)->where('id', $user['country_id'] ?? 0)->find();
        $this->assign('country', $country);
        $this->assign('datetime_txt', json_encode($datetimes));

        return $this->fetch($template);
    }

    //会员信息设置
    public function profile()
    {
        $user = Users::find($this->user_id);
        if ($this->request->isAjax()) {
            $act = input('act');
            $data = $this->request->post();
            if ($act == 'edit_profile') {
                //修改个人资料
                $ret = Users::edit_profile($data, $user);
                echo json_encode($ret);
                exit;
            } elseif ($act == 'edit_pass') {
                //修改密码
                $ret = Users::edit_pass($data, $user);
                echo json_encode($ret);
                exit;
            }
        }
        if (!$user) {
            $this->redirect('member/logout');
        }
        if ($user['user_type'] == 2) {
            $locations = Country::where(['status' => 1, 'is_teacher'=>1])->order('id')->select();
        } else {
            $locations = Country::where('status', 1)->order('id')->select();
        }
        $this->assign('countrys', $locations);
        $locations = Location::where('status', 1)->order('id')->select();
        $this->assign('locations', $locations);
        if ($this->user_type == 1) {
            $english_level = config('english_level');
            $this->assign('english_level', $english_level);
            $native_language = config('native_language');
            $this->assign('native_language', $native_language);
        }
        $this->assign('user_info', $user);
        if ($this->isMobile()) {
            $act = input('act');
            if ($act == 'setting') {
                $template = 'profile_m';
            } elseif ($act == 'password') {
                $template = 'password';
            } else {
                $template = 'setting_m';
            }
        } else {
            $template = '';
        }

        return $this->fetch($template);
    }

    //账户流水
    public function accounts()
    {
        $act = input('act');
        $map = ['user_id' => $this->user_id];
        if ($act == 'withdrawal') {
            $config = ['query'=> ['act'=>'withdrawal']];
            $list = Withdrawal::where($map)->order('id desc')->paginate(20, false, $config);
            $this->assign('list', $list);
            $status = ['Submitted', 'Success','Error'];
            $this->assign('status_list', $status);
        } else {
            $list = Account::where($map)->order('id desc')->paginate(20);
            $this->assign('list', $list);
        }
        $list = $list->toArray();
        $this->assign('last_page', $list['last_page']);
        $this->assign('act', $act);

        $types = Db::name('cms_account_type')->cache(true)->column('id, type_name');
        $this->assign('types', $types);

        $user = Users::field('moneys, paypal_account,location')->where('id', $this->user_id)->find();
        $this->assign('user_info', $user);

        $this->assign('location_user', get_user_timezone());
        $template = 'accounts';
        if ($this->user_type == 2) {
            $template = 'accounts_tour';
        }
        if (input('ajax') == 1) {
            $template .= '_ajax';
        }
        return $this->fetch($template);
    }

    //课程记录，当天之前的
    public function classs()
    {
        $date2 = time_to_date(time(), get_user_timezone(), 'Y-m-d H:i:s');
        $time2 = strtotime($date2);
        $this->assign('time_now', $time2);
        $this->assign('date_now', $date2);

        $status = OrderStatus::column('id,status_name');
        $this->assign('status_list', $status);

        $state_id = input('state_id', 0);
        $map = [];
        $obj = Orderitems::alias('i')->field('i.*, username, location, country_id, descr, english_level,native_language, goals');
        if ($state_id) {
            $config = ['query'=> ['state_id'=>$state_id]];
            if ($this->user_type == 2) {
                if ($state_id == 2) {
                    $map[] = ['order_status', 'eq', $state_id];
                    $map[] = ['teacher_money', 'eq', 1];
                } elseif ($state_id == 3) {
                    $obj->where("order_status=3 OR (order_status=2 AND teacher_money=0)");
                } else {
                    $map[] = ['order_status', 'eq', $state_id];
                }
            } else {
                $map[] = ['order_status', 'eq', $state_id];
            }
        } else {
            $config = [];
            $map[] = ['order_status', 'between', [2,4]];
        }
        $status = OrderStatus::where('id', 'lt', 10)->column('id, status_name');
        $this->assign('status_list', $status);
        $this->assign('state_id', $state_id);

        $locations = Location::get_list_col();
        $this->assign('location_list', $locations);
        $countrys = Country::get_list_col();
        $this->assign('country_list', $countrys);
        $this->assign('location_list', $locations);
        $this->assign('location_user', get_user_timezone());
        if ($this->user_type == 2) {
            $map[] = ['teacher_id', 'eq', $this->user_id];
            //教师
            $list = $obj
                ->join('cms_users u', 'user_id = u.id')
                ->where($map)->order('i.datetime desc')->paginate(10, false, $config);
            $comment_txt = 'Learner';
        } else {
            $comment_txt = 'Turtor';
            $map[] = ['user_id', 'eq', $this->user_id];
            $list = $obj
                ->join('cms_users u', 'teacher_id = u.id')
                ->where($map)->order('i.datetime desc')->paginate(10, false, $config);
        }
        $this->assign('order_list', $list);
        $this->assign('comment_txt', $comment_txt);
        $list = $list->toArray();
        $this->assign('last_page', $list['last_page']);

        $countrys = Country::get_list_col();
        $english_level = config('english_level');
        $native_language = config('native_language');
        $this->assign('countrys', $countrys);
        $this->assign('english_level', $english_level);
        $this->assign('native_language', $native_language);
        if (input('ajax') == 1) {
            return $this->fetch('class_ajax');
        } else {
            return $this->fetch();
        }
    }

    //消息列表
    public function notices()
    {
        $map = ['user_id' => $this->user_id ];
        $list = Notice::where($map)->order('id desc')->paginate(5);
        $this->assign('list', $list);

        Notice::where($map)->setField('is_read', 1);

        $list = $list->toArray();
        $this->assign('last_page', $list['last_page']);

        $this->assign('location_user', get_user_timezone());
        if (input('ajax') == 1) {
            return $this->fetch('notices_ajax');
        } else {
            return $this->fetch();
        }
    }

    //预约记录，从当天开始的1个月内
    public function schedule()
    {
        //获取30天的日期
//        $dates = Orderitems::get_day_30($this->user_id, $this->user_type);
//        $this->assign('dates', $dates);

        $locaiton = get_user_timezone();
        $time = time();
        $date = time_to_date($time, $locaiton, 'Y-m-d');
        $date2 = time_to_date(time(), get_user_timezone(), 'Y-m-d H:i:s');
        $time2 = strtotime($date2);
        $this->assign('time_now', $time2);
        $this->assign('date_now', $date2);

        $user = Users::find($this->user_id);
        $user['md5'] = md5($user['password']);

        $app = config('app_android_apk');
        if ($app) {
            $apk = Attachment::find($app);
            $apk = '/public/'.$apk['path'];
        } else {
            $apk = '';
        }
        $this->assign('apk_downfile', $apk);
        $this->assign('user_info', $user);

        if ($this->user_type == 1) {
            //学生
            $map = [ ['i.user_id', 'eq', $this->user_id], ['book_date', 'egt', $date], ['i.order_status','eq', 1] ];
            $addstr = '';
        } else {
            $map = [ ['i.teacher_id', 'eq', $this->user_id], ['book_date_teacher', 'egt', $date], ['i.order_status','eq', 1] ];
            $addstr = '_teacher';
        }
        $list = Orderitems::get_list($map, 1);
        $datetimes = [];
        foreach ($list as $k => $row) {
            $datetimes[] = ["datetime" => strtotime($row['book_date' . $addstr].' '.$row['time_begin' . $addstr]), "booked" => 1, "date" => $row['book_date' . $addstr], "time" => $row['time_begin' . $addstr],'teacher_id'=>$row['teacher_id'], "time_end" => $row['time_end' . $addstr]];
        }
        $this->assign('datetime_txt', json_encode($datetimes));
        $this->assign('class_list', $list);
        $this->assign('location_user', $locaiton);

        return $this->fetch();
    }

    //预约记录，从当天开始的1个月内
    public function schedule2()
    {
        //获取30天的日期
//        $dates = Orderitems::get_day_30($this->user_id, $this->user_type);
//        $this->assign('dates', $dates);

        $locaiton = get_user_timezone();
        $time = time();
        $date = time_to_date($time, $locaiton, 'Y-m-d');
        $date2 = time_to_date(time(), get_user_timezone(), 'Y-m-d H:i:s');
        $time2 = strtotime($date2);
        $this->assign('time_now', $time2);
        $this->assign('date_now', $date2);

        if ($this->user_type == 1) {
            //学生
            $map = [ ['i.user_id', 'eq', $this->user_id], ['book_date', 'egt', $date], ['i.order_status','eq', 1] ];
            $addstr = '';
        } else {
            $map = [ ['i.teacher_id', 'eq', $this->user_id], ['book_date_teacher', 'egt', $date], ['i.order_status','eq', 1] ];
            $addstr = '_teacher';
        }
        $list = Orderitems::get_list($map, 1);
        $datetimes = [];
        foreach ($list as $k => $row) {
            $datetimes[] = ["datetime" => strtotime($row['book_date' . $addstr].' '.$row['time_begin' . $addstr]), "booked" => 1, "date" => $row['book_date' . $addstr], "time" => $row['time_begin' . $addstr],'teacher_id'=>$row['teacher_id'], "time_end" => $row['time_end' . $addstr]];
        }
        $this->assign('datetime_txt', json_encode($datetimes));
        $this->assign('class_list', $list);
        $this->assign('location_user', $locaiton);

        return $this->fetch();
    }

    //获取某一天的课程列表
    public function get_list($date)
    {
        $index = input('index', 0);
        $size = 20;
        if ($index) {
            $size = 10;
        }
        $this->assign('index', $index);
        $countrys = Country::get_list_col();
        $locations = Location::get_list_col();
        $english_level = config('english_level');
        $native_language = config('native_language');
        $date = date('Y-m-d', strtotime($date));
        $user_id = $this->user_id;
        $user_type = $this->user_type;
        $time = strtotime('-30 minute');
        $date_now = time_to_date($time, get_user_timezone(), 'Y-m-d H:i');
        $dates = explode(' ', $date_now);
//        print_r($dates);print_r(get_user_timezone());
        if ($user_type == 1) {
            $map = [ ['user_id', 'eq', $user_id], ['book_date', 'eq', $date]];
            $join_col = 'teacher_id';
            $field = 'i.*, goals,username,native_language,english_level,location as location_id_s,descr as descr, country_id, goals';
            if ($dates[0] == $date) {
                //如果是当天的，只显示当前时间后的
                $map[] = ['time_begin', 'gt', $dates[1]];
            }
        } else {
            $field = 'i.*, goals,username,native_language,english_level,location as location_id_s,descr as descr, country_id, goals';
            $map = [ ['teacher_id', 'eq', $user_id], ['book_date_teacher', 'eq', $date]];
            $join_col = 'user_id';
            if ($dates[0] == $date) {
                //如果是当天的，只显示当前时间后的
                $map[] = ['time_begin_teacher', 'gt', $dates[1]];
            }
        }
        $map[] = ['order_status', 'eq', 1];
        $list = Orderitems::alias('i')->field($field)
            ->join('cms_users u', "{$join_col} = u.id")
            ->where($map)->order('i.datetime')->paginate($size, false, [
                'query' => ['date'=>$date]
            ]);
        $lists = $list->toArray();
        if ($user_type == 1) {
            $out = $lists['data'];
        } else {
            $out = [];
            foreach ($lists['data'] as $k => $row) {
                $out[$k] = $row;
                $out[$k]['first'] = $native_language[$row['native_language']];
                $out[$k]['levels'] = $english_level[$row['english_level']];
                $out[$k]['location_name'] = $countrys[$row['country_id']]['country_name'] ?? '';
                $out[$k]['location_ico'] = $countrys[$row['country_id']]['ico_file'] ?? '';
            }
        }
        $this->assign('lists', $out);
        $this->assign('list', $list);

        $time3 = strtotime('+'. config('cfg_cancel_time').' hour');
        $this->assign('time3', $time3);
        return $this->fetch();
    }

    //修改课节时间-打开窗口
    public function change_time()
    {
        $id = input('id');
        $info = Orderitems::where(['id' => $id, 'user_id' => $this->user_id])->find();
        if (!$info) {
            $this->redirect('schedule');
        }
        $this->assign('class_info', $info);
        $teacher = Users::find($info['teacher_id']);
        $this->assign('teacher', $teacher);
        $location_country = Country::find($teacher['country_id']);
        $this->assign('location_country', $location_country);
        $location_teacher = Location::find($teacher['location']);
        $this->assign('location_teacher', $location_teacher);

        $location_login = get_user_timezone();
        $daytimes = Daytime::get_day_30($info['teacher_id'], $location_teacher, $location_login, $this->user_id);
        $this->assign('daytimes', json_encode($daytimes));
        $ajax = input('ajax', 0);
        if ($ajax) {
            $time_zone = change_time($location_teacher['timezone']);
            $ret = ['daytimes' => $daytimes, 'teacher' => $teacher, 'location_teacher' =>$location_teacher, 'location_country' =>$location_country ];
            $ret['class'] = $info;
            echo json_encode($ret);
        } else {
            return $this->fetch();
        }
    }

    //修改课节时间
    public function to_change()
    {
        $id = input('id');
        $daytime_id = input('daytime_id');
        if (!$id || !$daytime_id) {
            $ret = ['code' => 201, 'msg' => 'Please select time'];
        } else {
            $location_login = get_user_timezone();
            $ret = Orderitems::edit_item($id, $this->user_id, $daytime_id, $location_login);
        }
        echo json_encode($ret);
    }

    //日历，老师设置可上课时间，1个月内的
    public function calendar()
    {
        if ($this->user_type != 2) {
            $this->redirect('member/index');
        }
        $location_teacher = get_user_timezone();
        $now = time();
        $date = time_to_date($now, $location_teacher, 'Y-m-d H:i');
        $this->assign('date_now', $date);
        $this->assign('location', $location_teacher);
        $arr = explode(' ', $date);
        $date = $arr[0];
        $datetimes = Daytime::get_teacher_time($this->user_id, $date);
        $this->assign('datetimes', $datetimes);

        $date2 = time_to_date(time(), get_user_timezone(), 'Y-m-d H:i:s');
        $time2 = strtotime($date2);
        $this->assign('time_now', $time2);
        $this->assign('date_now', $date2);
        return $this->fetch();
    }

    public function calendarnew()
    {
        if ($this->user_type != 2) {
            $this->redirect('member/index');
        }
        $location_teacher = get_user_timezone();
        $now = time();
        $date = time_to_date($now, $location_teacher, 'Y-m-d H:i');
        $this->assign('date_now', $date);
        $this->assign('location', $location_teacher);
        $arr = explode(' ', $date);
        $date = $arr[0];
        $datetimes = Daytime::get_teacher_time($this->user_id, $date);
        $this->assign('datetimes', $datetimes);

        $date2 = time_to_date(time(), get_user_timezone(), 'Y-m-d H:i:s');
        $time2 = strtotime($date2);
        $this->assign('time_now', $time2);
        $this->assign('date_now', $date2);
        return $this->fetch();
    }
    //confirm chat
    public function confirm($id = 0)
    {
        $ret = Orderitems::confirm($id, $this->user_id);
        echo json_encode($ret);
    }
    
    //取消课程
    public function cancel($id = 0)
    {
        $ret = Orderitems::cancel($id, $this->user_id, $this->user_type);
        echo json_encode($ret);
    }

    //老师设置上课时间
    public function set_times()
    {
        if ($this->user_type == 1) {
            echo json_encode(['code' => 201, 'msg' => 'Please login as a tutor']);
            exit;
        }
        $date = input('date');
        $times = input('times/a', []);
        $days = input('days/a', []);
        if (!$date) {
            $ret = ['code' => 201, 'msg' => 'Please select Date'];
        } else {
            $obj = new Daytime();
            $ret = $obj->adds($date, $times, $days, $this->user_id);
        }
        echo json_encode($ret);
    }

    //退出登录
    public function logout()
    {
        session('user_id', null);
        session('user_type', null);
        session_destroy();
        cookie('user_type', 0);
        cookie('is_partner', 0);
        $this->redirect('/');
    }

    //修改提现账号
    public function edit_account()
    {
        if ($this->request->isAjax()) {
            $ret = Users::edit_pay_account($this->user_id);
        } else {
            $ret = ['code' => 201, 'msg' => 'System error!' ];
        }
        echo json_encode($ret);
    }

    //提现
    public function withdrawal()
    {
        if ($this->request->isPost()) {
            $obj = new Withdrawal();
            $ret = $obj->cashout($this->user_id, input('money'));
            echo json_encode($ret);
            exit;
        }
        $user = Users::find($this->user_id);
        $this->assign('user_info', $user);
        return $this->fetch();
    }

    //捐赠
    public function donate()
    {
        $device_type = get_device_type();
        if ($this->request->isPost()) {
            $obj = new Donation();
            $user = Users::find($this->user_id);
            $money = input('money');
            $pay_type = input('pay_type', 0);
            $ret = $obj->to_send($user, $money, $pay_type);
            echo json_encode($ret);
            exit;
        }
        $user = Users::find($this->user_id);
        $this->assign('user_info', $user);

        $device_type = get_device_type();
        $is_wechat_browser = 1;
        if ($device_type > 1) {
            if (!is_wechat_browser()) {
                $is_wechat_browser = 0;
            }
        }
        $this->assign('is_wechat_browser', $is_wechat_browser);
        return $this->fetch();
    }
  
//topup 202401124  
   public function topup()
    {
        $device_type = get_device_type();
        if ($this->request->isPost()) {
            $obj = new Topup();
            $user = Users::find($this->user_id);
            $money = input('money');
            $pay_type = input('pay_type', 0);
            $ret = $obj->to_send_topup($user, $money, $pay_type);
            echo json_encode($ret);
            exit;
        }
        $user = Users::find($this->user_id);
        $this->assign('user_info', $user);

        $device_type = get_device_type();
        $is_wechat_browser = 1;
        if ($device_type > 1) {
            if (!is_wechat_browser()) {
                $is_wechat_browser = 0;
            }
        }
        $this->assign('is_wechat_browser', $is_wechat_browser);
        return $this->fetch();
    }
    //老师设置关闭、打开
    public function set_state()
    {
        $close_state = input('close_state');
        Users::where('id', $this->user_id)->setField('close_state', $close_state);
        echo json_encode( ['code' => '200', 'msg' => 'success'] );
    }

    //打开classin,进入课程
    public function enter_class($id = 0)
    {
        $info = Orderitems::find($id);
        if ($info['user_id'] != $this->user_id && $info['teacher_id'] != $this->user_id && $info['order_status'] > 1 ) {
            $this->redirect('member/index');
        }
        $res = Orderitems::get_link($this->user_id, $info);
        if ($res['code'] == 200) {
            header("location:". $res['link']);
        } else {
            $this->error($res['msg'], url('member/index'));
        }
    }

    public function share()
    {
        $user = Users::find($this->user_id);
        $this->assign('user_info', $user);

        return $this->fetch();
    }

    public function check_time($date, $time, $dayid, $teacher_id)
    {
        $time_begin = $time;
        $user_id = $this->user_id;
        $time = strtotime($date);
        $w = date('w', $time);
        $no = 1;
        $dayinfo = Daytime::find($dayid);
        $error_teacher = 0;
        $error_learner = 0;

        $end_date = date('Y-m-d', strtotime('+7 day', strtotime($dayinfo['date']) ));
        $end_date_user = date('Y-m-d', strtotime('+7 day'));
        $teacher = Daytime::where(['user_id' => $teacher_id, 'booked' => 0, 'time'=>$dayinfo['time']])->where('date','between',[$dayinfo['date'], $end_date])->count();
//        echo Daytime::getlastsql();
        if ($teacher < 7) {
            $error_teacher = 1;
            echo json_encode(['error_teacher' => $error_teacher, 'error_learner' => $error_learner]);
            exit;
        }
        $has_leaner = Orderitems::where(['user_id'=>$user_id, 'time_begin' => $time_begin, 'order_status' => 1])->where('book_date', 'between',[$date, $end_date_user])->find();
        if ($has_leaner) {
            $error_learner = 1;
        }
//        echo Orderitems::getlastsql();
        echo json_encode(['error_teacher' => $error_teacher, 'error_learner' => $error_learner]);
        exit;
        while($no < 7) {
            $date_new = date('Y-m-d', strtotime('+'.$no.' day', $time));
            $time_new = strtotime('+'.$no.' day', $dayinfo['datetime']);
            $has_teacher = Daytime::where(['user_id' => $teacher_id, 'booked' => 0, 'datetime'=>$time_new])->find();
            if (!$has_teacher) {
                $error_teacher = 1;
                break;
            }
            $has_leaner = Orderitems::where(['user_id'=>$user_id, 'book_date' => $date_new, 'time_begin' => $time_begin, 'order_status' => 1])->find();
            if ($has_leaner) {
                $error_learner = 1;
                break;
            }
            $no++;$w++;
        }
        if ($no < 7) {
            $error_teacher = 1;
        }
        echo json_encode(['error_teacher' => $error_teacher, 'error_learner' => $error_learner]);
    }

    public function orders()
    {
        $user_id = $this->user_id;
        $orders = Order::alias('o')->field('o.*,username,p.id as pay_id')
            ->join('cms_users m', 'teacher_id = m.id')
            ->join('cms_payment p', 'obj_id = o.id and type=1', 'left')
            ->where('o.user_id', $user_id)->order('o.id desc')->paginate(10);
        foreach ($orders as $k=>$row) {
            $items = Orderitems::where('order_id', $row['id'])->order('id')->select();
            $orders[$k]['items'] = $items;
        }
        $this->assign('lists', $orders);
        $list = $orders->toArray();
        $this->assign('last_page', $list['last_page']);
        if (input('ajax') == 1) {
            return $this->fetch('orders_ajax');
        } else {
            return $this->fetch();
        }
    }

    public function to_cancel()
    {
        $order_id = input('order_id');
        $obj = new \app\index\logic\Order();
        $ret = $obj::cancel($order_id);
        echo json_encode($ret);
    }

    public function clearar()
    {
        Daytime::clearar($this->user_id);
        echo 'success';
    }

    //获取课程信息，生成二维码
    public function get_room($class_id = 0)
    {
        $ret = Orderitems::get_room($this->user_id, $class_id);
        echo $ret;
    }

    public function pdf()
    {
        $time = time();
        $date2 = time_to_date($time, get_user_timezone(), 'Y-m-d');
        $name = url_base64_encode(input('name'));
        $date_start = str_replace('/', '-', input('date_start'));
        $date_end = str_replace('/', '-', input('date_end'));

        $url = url('pdf/index', ['name'=>$name, 'uid'=>$this->user_id, 'date' => $date2, 'start'=>$date_start, 'end'=>$date_end]);
        $weburl = 'https://wespeakenglish.chat';
        $url = $weburl.$url;
        $fname = '/public/pdf/Tutoring_'.$time.'.pdf';
        $fnameall = $weburl.$fname;
        $cmd = 'wkhtmltopdf -q "'.$url.'" '.$_SERVER['DOCUMENT_ROOT'].$fname;
        $res = shell_exec($cmd);
        $act = input('act');
        if ($act == 'email') {
            $content = file_get_contents("template/report.html");
            $find = ['{download}', '{name}'];
            $replace = [$fnameall, $name];
            $content = str_replace($find, $replace, $content);
            $user = Users::find($this->user_id);
            $res = send_email_g($user['email'], 'My tutoring report', $content);
            if ($res['code'] == 0) {
                $this->success('Send successfully');
            } else {
                $this->success('Sending failed');
            }
        } else {
            $this->redirect($fname);
        }
    }

}