<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2021/5/20
 * Time: 10:34
 */

namespace app\index\controller;

use app\index\model\Account;
use app\index\model\Country;
use app\index\model\Orderitems;
use app\index\model\Users;
use app\index\model\Withdrawal;
use think\Db;

class Partner extends Home
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $user_id = session('user_id');
        $this->chk_login($user_id);
        $this->user_type = session('user_type');
        if (session('is_partner') != 1) {
            $this->redirect('member/index');
        }
        $time = time();
        $date2 = time_to_date($time, get_user_timezone(), 'Y-m-d H:i:s');
        $time2 = strtotime($date2);
        $this->assign('time_now', $time2);
        $this->assign('date_now', $date2);
        $this->assign('is_partner', 1);
    }

    public function index()
    {
        $user = Users::find($this->user_id);
        $this->assign('user_info', $user);

        if ($this->user_type == 1) {
            //学生
            $col = 'user_id';
            $url = url('register/learner', ['partner' => $user['classin_uid']]);
        } else {
            $col = 'teacher_id';
            $url = url('register/tutor', ['partner' => $user['classin_uid']]);
        }
        $this->assign('reg_url', $url);
        $chats = Orderitems::get_list_partner($this->user_id, $this->user_type, 2, 8, 0);
        $this->assign('chat_lists', $chats);

        $user_num = Users::where(['partner_id'=>$this->user_id, 'status' => 1, 'user_type'=>$this->user_type])->count();
        $this->assign('user_num', $user_num);

        if ($this->user_type == 1) {
            $field = 'class_num, class_num as has_active, native_language, english_level, country_id,descr, goals';

            $english_level = config('english_level');
            $native_language = config('native_language');
            $countrys = Country::cache(true)->column('id, country_name');
            $this->assign('english_levels', $english_level);
            $this->assign('countrys', $countrys);
            $this->assign('native_languages', $native_language);
        } else {
            $field = 'class_num, has_active';
        }
        $childs = Users::field('id, username,star, close_state, '.$field)->where(['partner_id'=>$this->user_id, 'status' => 1, 'user_type'=>$this->user_type])->order('id desc')->limit(5)->select();
        $this->assign('childs', $childs);

        $class_num = Orderitems::alias('o')->where('order_status', 'in', [2])->join('cms_users u', $col.' = u.id and partner_id = '.$this->user_id)->count();
        $this->assign('class_num', $class_num);

        $web_site_url = 'https://'.$_SERVER['SERVER_NAME'];
        $this->assign('web_site_url', $web_site_url);

        return $this->fetch();
    }

    //会员信息设置
    public function profile()
    {
        $user = Users::find($this->user_id);
        if ($this->request->isAjax()) {
            $act = input('act');
            $data = $this->request->post();
            if ($act == 'edit_profile') {
                //修改个人资料
                $ret = Users::edit_profile_partner($data, $user);
                echo json_encode($ret);
                exit;
            } elseif ($act == 'edit_pass') {
                //修改密码
                $ret = Users::edit_pass($data, $user);
                echo json_encode($ret);
                exit;
            }
        }
        if (!$user) {
            $this->redirect('partner/logout');
        }
        if ($user['user_type'] == 2) {
            $locations = Country::where(['status' => 1, 'is_teacher'=>1])->order('id')->select();
            $proinces = Db::name('cms_regions')->where(['country_id' => $user['country_id'], 'parent_id'=>0 ])->order('id')->select();
            $citys = Db::name('cms_regions')->where(['country_id' => $user['country_id'], 'parent_id'=>$user['province'] ])->order('id')->select();
            $this->assign('provinces', $proinces);
            $this->assign('citys', $citys);
        } else {
            $locations = Country::where('status', 1)->order('id')->select();
        }
        $this->assign('countrys', $locations);
        $this->assign('user_info', $user);
        if ($this->isMobile()) {
            $act = input('act');
            if ($act == 'setting') {
                $template = 'profile_m';
            } elseif ($act == 'password') {
                $template = 'password';
            } else {
                $template = 'setting_m';
            }
        } else {
            $template = '';
        }

        return $this->fetch($template);
    }

    //课程列表
    public function chats()
    {
        $date = input('date', date('Y.m'));
        $date = str_replace('.','-', $date);
        if ($this->user_type == 1) {
            $map = "substr(book_date, 1, 7)='$date'";
        } else {
            $map = "substr(book_date_teacher, 1, 7)='$date'";
        }
//        $map = "FROM_UNIXTIME(datetime, '%Y.%m') = '$date'";
        $list = Orderitems::get_list_partner($this->user_id, $this->user_type, 2, 20, 1, $map);
        $this->assign('lists', $list);

        $act = input('act');
        if ($act == 'total') {
            $list = $list->toArray();
            echo $list['total'];
            exit;
        } elseif (input('ajax') == 1) {
            return $this->fetch('chats_ajax');
        } else {
            $list = $list->toArray();
            $this->assign('total', $list['total']);

            return $this->fetch();
        }
    }

    //客户列表
    public function members()
    {
        $active = input('active');
        $map = ['partner_id'=>$this->user_id, 'status' => 1, 'user_type'=>$this->user_type];
        if ($this->user_type == 1) {
            $field = 'class_num, class_num as has_active, native_language, english_level, country_id,descr, goals';
            $key = 'class_num';
        } else {
            $key = 'has_active';
            $field = 'class_num, has_active';
        }
        $obj = Users::field('id, username,star, close_state, '.$field)->where($map);
        if ($active == 1) {
            $obj->where($key, 'gt', 0);
        } elseif ($active == 2) {
            $obj->where($key, 0);
        }
        $list = $obj->order('id desc')->paginate(15);
        $this->assign('lists', $list);
        $this->assign('active', $active);

        if (input('ajax') == 1) {
            return $this->fetch('members_ajax');
        } else {
            $title_list = $this->user_type == 1 ? 'Learners' : 'Tutors';
            $list = $list->toArray();
            $this->assign('total', $list['total']);
            $this->assign('title_list', $title_list);

            if ($this->user_type == 1) {
                $field = 'class_num';
            } else {
                $field = 'has_active as class_num';
            }
            $total_active = $obj = Users::field('id, username,star, close_state, '.$field)->where($map)->where('class_num|has_active', 'gt', 0)->count();
            $this->assign('total_active', $total_active);
            return $this->fetch();
        }
    }

    //提现
    public function withdrawal()
    {
        if ($this->request->isPost()) {
            $obj = new Withdrawal();
            $ret = $obj->cashout($this->user_id, input('money'));
            echo json_encode($ret);
            exit;
        }
        $user = Users::find($this->user_id);
        $this->assign('user_info', $user);
        return $this->fetch();
    }

    //捐赠
    public function donate()
    {
        $device_type = get_device_type();
        if ($this->request->isPost()) {
            $obj = new Donation();
            $user = Users::find($this->user_id);
            $money = input('money');
            $pay_type = input('pay_type', 0);
            $ret = $obj->to_send($user, $money, $pay_type);
            echo json_encode($ret);
            exit;
        }
        $user = Users::find($this->user_id);
        $this->assign('user_info', $user);

        $device_type = get_device_type();
        $is_wechat_browser = 1;
        if ($device_type > 1) {
            if (!is_wechat_browser()) {
                $is_wechat_browser = 0;
            }
        }
        $this->assign('is_wechat_browser', $is_wechat_browser);
        return $this->fetch();
    }
   public function topup()
    {
        $device_type = get_device_type();
        if ($this->request->isPost()) {
            $obj = new Topup();
            $user = Users::find($this->user_id);
            $money = input('money');
            $pay_type = input('pay_type', 0);
            $ret = $obj->to_send($user, $money, $pay_type);
            echo json_encode($ret);
            exit;
        }
        $user = Users::find($this->user_id);
        $this->assign('user_info', $user);

        $device_type = get_device_type();
        $is_wechat_browser = 1;
        if ($device_type > 1) {
            if (!is_wechat_browser()) {
                $is_wechat_browser = 0;
            }
        }
        $this->assign('is_wechat_browser', $is_wechat_browser);
        return $this->fetch();
    }
    //账户流水
    public function accounts()
    {
        $act = input('act');
        $map = ['user_id' => $this->user_id];
        if ($act == 'withdrawal') {
            $list = Withdrawal::where($map)->order('id desc')->paginate(20);
            $this->assign('list', $list);
            $status = ['Submitted', 'Success','Error'];
            $this->assign('status_list', $status);
        } else {
            $list = Account::where($map)->order('id desc')->paginate(20);
            $this->assign('list', $list);
        }
        $list = $list->toArray();
        $this->assign('last_page', $list['last_page']);
        $this->assign('act', $act);

        $types = Db::name('cms_account_type')->cache(true)->column('id, type_name');
        $this->assign('types', $types);

        $user = Users::field('moneys, paypal_account,location')->where('id', $this->user_id)->find();
        $this->assign('user_info', $user);

        $this->assign('location_user', get_user_timezone());
        $template = 'accounts';
        if ($this->user_type == 2) {
//            $template = 'accounts_tour';
        }
        if (input('ajax') == 1) {
            $template .= '_ajax';
        }
        return $this->fetch($template);
    }

    //帮助
    public function helps()
    {
        return $this->fetch();
    }

    //发送验证码
    public function send_email()
    {
        $ret = Users::send_code($this->user_id);
        echo json_encode($ret);
    }

    //退出登录
    public function logout()
    {
        session('user_id', null);
        session('user_type', null);
        session_destroy();
        cookie('user_type', 0);
        cookie('is_partner', 0);
        $this->redirect('/');
    }

    //协议
    public function pdf()
    {
        $user = Users::find($this->user_id);
        $date2 = time_to_date($user['create_time'], get_user_timezone(), 'Y-m-d');

        $url = url('pdf/agree', ['uid'=>$this->user_id, 'date' => $date2]);
        $weburl = 'https://wespeakenglish.chat';
        $url = $weburl.$url;
        $fname = '/public/pdf/agree_'.$this->user_id.'.pdf';
        if (is_file('.'.$fname)) {
            $this->redirect($fname);
        } else {
            $fnameall = $weburl . $fname;
            $cmd = 'wkhtmltopdf -q "' . $url . '" ' . $_SERVER['DOCUMENT_ROOT'] . $fname;
            $res = shell_exec($cmd);

            $this->redirect($fname);
        }
    }



}