<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/10/29
 * Time: 17:16
 */

namespace app\index\controller;

use app\index\model\Country;
use app\index\model\Location;
use app\index\model\Users;
use think\Db;

class Register extends Home
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if ($this->user_id > 0) {
            $this->redirect('member/index');
        }
        $teacher_id = session('teacher_id_jump');
        if ($teacher_id) {
            $continue_url = url('tutors/detail', ['teacher_id'=>$teacher_id]);
            $this->assign('continue_url', $continue_url);
        }
    }

    //老师注册页面
    public function tutor()
    {
        $locations = Location::where('status', 1)->order('timezone +0, location_name,id')->select();
        $this->assign('locations', $locations);

        $locations = Country::where(['status' => 1, 'is_teacher'=>1])->order('id')->select();
        $this->assign('countrys', $locations);

        return $this->fetch();
    }

    //学生注册页面
    public function learner()
    {
        $locations = Location::where('status', 1)->order('timezone +0, location_name,id')->select();
        $this->assign('locations', $locations);

        $locations = Country::where('status', 1)->order('id')->select();
        $this->assign('countrys', $locations);

        $english_level = config('english_level');
        $this->assign('english_level', $english_level);
        $native_language = config('native_language');
        $this->assign('native_language', $native_language);

        return $this->fetch();
    }

    //机构注册页面
    public function partner()
    {
        $locations = Location::where('status', 1)->order('timezone +0, location_name,id')->select();
        $this->assign('locations', $locations);

        $locations = Country::where(['status' => 1, 'is_teacher'=>1])->order('id')->select();
        $this->assign('countrys', $locations);

        $locations = Country::where('status', 1)->order('id')->select();
        $this->assign('countrys2', $locations);

        $english_level = config('english_level');
        $this->assign('english_level', $english_level);
        $native_language = config('native_language');
        $this->assign('native_language', $native_language);

        $this->assign('is_partner', 1);

        return $this->fetch();
    }

    //学生注册
    public function post_learner()
    {
        $data = input('post.');
        $obj = new Users();
        $lang = get_language();
        $lang = 'en';
        $ret = $obj->register_studuent($data, $lang);
        echo json_encode($ret);
    }

    //老师注册
    public function post_tutor()
    {
        $data = input('post.');
        $obj = new Users();
        $ret = $obj->register_teacher($data);
        echo json_encode($ret);
    }

    //机构注册
    public function post_partner()
    {
        $data = input('post.');
        $obj = new Users();
        $ret = $obj->register_parnter($data);
        echo json_encode($ret);
    }

    public function resend($email = '')
    {
        $obj = new Users();
        $ret = $obj->resend($email);
        if ($ret['code'] == 0) {
            $ret['code'] = 200;
            $ret['msg'] = 'Please check your email for verification. Maybe in the Junk folder. If you cannot find the email, it is likely you typed the wrong email, please sign up again with the correct email.';
        } else {
            $ret['msg'] = 'Send error';
        }
        echo json_encode($ret);
    }

    //获取州、市
    public function get_regions($pid, $type)
    {
        if ($type == 1) {
            $map = ['country_id' => $pid, 'parent_id' => 0];
        } else {
            $map = ['parent_id' => $pid];
        }
        $list = Db::name('cms_regions')->where($map)->order('region_name')->select();
        echo json_encode($list);
    }


}