<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/10/29
 * Time: 17:16
 */

namespace app\index\controller;

use app\cms\model\Advert;
use app\index\model\Users;
use think\App;

class Sign extends Home
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if ($this->user_id > 0) {
            $this->redirect('member/index');
        }
        $teacher_id = session('teacher_id_jump');
        if ($teacher_id) {
            $continue_url = url('tutors/detail', ['teacher_id'=>$teacher_id]);
            $this->assign('continue_url', $continue_url);
        }
    }

    //老师登录页面
    public function tutor()
    {
        $ads_top = Advert::where(['typeid' => 7, 'status' => 1])->order('id desc')->find();
        $this->assign('ads', $ads_top);

        $this->assign('type', 2);

        return $this->fetch();
    }

    //机构
    public function partner()
    {
//        $ads_top = Advert::where(['typeid' => 10, 'status' => 1])->order('id desc')->find();
//        $this->assign('ads', $ads_top);

        $continue = input('continue');
        $this->assign('continue', $continue);

        $this->assign('type', 3);
        $this->assign('is_partner', 1);
        return $this->fetch();
    }

    //学生登录页面
    public function learner()
    {
        $ads_top = Advert::where(['typeid' => 6, 'status' => 1])->order('id desc')->find();
        $this->assign('ads', $ads_top);
        $continue = input('continue');
        $this->assign('continue', $continue);
//        $url = url_base64_decode($continue);
//        $this->assign('continue_url', $url);

        $this->assign('type', 1);

        return $this->fetch();
    }

    //学生登录
    public function post_learner()
    {
        $data = input('post.');
        $obj = new Users();
        $ret = $obj->signin($data, 1);
        echo json_encode($ret);
    }

    //老师登录
    public function post_tutor()
    {
        $data = input('post.');
        $obj = new Users();
        $ret = $obj->signin($data, 2);
        echo json_encode($ret);
    }

    //机构登录
    public function post_partner()
    {
        $data = input('post.');
        $obj = new Users();
        $ret = $obj->signin($data, 2, 0, 1);
        echo json_encode($ret);
    }


}