<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/10/30
 * Time: 14:48
 */

namespace app\index\controller;

use app\index\logic\Tutor;
use app\index\model\Country;
use app\index\model\Daytime;
use app\index\model\Location;
use app\index\model\Order;
use app\index\model\Orderitems;
use app\index\model\Users;

class Tutors extends Home
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->user_type = session('user_type');
        $this->assign('user_type', $this->user_type);

        $date2 = time_to_date(time(), get_user_timezone(), 'Y-m-d H:i:s');
        $time2 = strtotime($date2);
        $this->assign('time_now', $time2);
    }

    public function index()
    {
        if ($this->user_id && $this->user_type == 1) {
            Users::where('id', $this->user_id)->setInc('search_cnt', 1);
            Users::where('id', $this->user_id)->setField('search_time', time());
        }
        $obj = new Tutor();
        if (isset($_GET['page'])) {
            $_POST['page'] = $_GET['page'];
        }

        $location_id = session('?location') ? session('location') : 0;
        if ($location_id) {
            $location_current = Location::find($location_id);
        } else {
            $location_current = Location::where('id', config('cfg_default_location'))->find();
        }
        $this->assign('location_current', $location_current);

        $order = input('order');
        $location = input('location/a', []);
        $this->assign('order', $order);
        $this->assign('location', $location);

        $locations = Location::cache(true)->where(['status' => 1])->select();
        $this->assign('locations', $locations);

        $locations = Country::cache(true)->where(['status' => 1, 'is_teacher'=>1, 'is_delete'=>0])->select();
        $this->assign('countrys', $locations);

//        $times = input('times/a');
        $times_count = 0;
        $this->assign('times_count', $times_count);
        $list = $obj->get_list($location_current);
        $this->assign('list', $list);
        $list = $list->toArray();
        $this->assign('last_page', $list['last_page']);
        $ajax = input('ajax');
        if ($ajax) {
            return $this->fetch('list');
        }

        return $this->fetch();
    }

    public function detail($teacher_id = 0)
    {
        session('teacher_id_jump', $teacher_id);
        if (!$this->user_id) {
            $url = url_base64_encode(url('detail', ['teacher_id' => $teacher_id]));
            $this->redirect('sign/learner', ['continue'=>$url]);
        }
        $login_user = Users::find($this->user_id);
        $this->assign('login_user', $login_user);

        $teacher = Users::find($teacher_id);
        if (!$teacher || !$teacher['email_verify'] || !$teacher['status'] || $teacher['is_locked']) {
            $this->redirect('index');
        }
        $location_login = get_user_timezone();
        $this->assign('location_login', $location_login);
        if (input('ajax') == 1) {
            $comment_list = Orderitems::get_comment_list(['teacher_id' => $teacher_id]);
            $this->assign('comment_list', $comment_list);
            return $this->fetch('get_comment_list');
        }

        $this->assign('teacher_info', $teacher);
        $location = Location::find($teacher['location']);
        $this->assign('location_teacher', $location);
        $location = Country::find($teacher['country_id']);
        $this->assign('country_teacher', $location);

//        $date = time_to_date(time(), $location_login, 'Y-m-d H:i:s');
//        echo $date;
        $date = time_to_date(time(), $location_login, 'Y-m-d');
        $dates = explode('-', $date);
        $this->assign('dates', $dates);

//        $daytimes = Daytime::get_day_30($teacher_id, $location, $location_login, $this->user_id);
//        $this->assign('daytimes', json_encode($daytimes));

        $cnt = Orderitems::alias('c')->where(['teacher_id' => $teacher_id])->where('comment_student_time', 'gt', 0)->count();
        $this->assign('cnt', $cnt);

        $comment_list = Orderitems::get_comment_list(['teacher_id' => $teacher_id]);
        $this->assign('comment_list', $comment_list);

        $date2 = time_to_date(time(), get_user_timezone(), 'Y-m-d H:i:s');
        $time2 = strtotime($date2);
        $this->assign('time_now', $time2);
        $this->assign('date_now', $date2);

        return $this->fetch();
    }

    public function get_daytimes($teacher_id)
    {
        $location_login = get_user_timezone();
        $daytimes = Daytime::get_day_30($teacher_id, [], $location_login, $this->user_id);
        echo json_encode($daytimes);
    }
    
    public function detailnew($teacher_id = 0)
    {
        session('teacher_id_jump', $teacher_id);
        if (!$this->user_id) {
            $url = url_base64_encode(url('detail', ['teacher_id' => $teacher_id]));
            $this->redirect('sign/learner', ['continue'=>$url]);
        }
        $login_user = Users::find($this->user_id);
        $this->assign('login_user', $login_user);

        $teacher = Users::find($teacher_id);
        if (!$teacher || !$teacher['email_verify'] || !$teacher['status'] || $teacher['is_locked']) {
            $this->redirect('index');
        }
        $location_login = get_user_timezone();
        $this->assign('location_login', $location_login);
        if (input('ajax') == 1) {
            $comment_list = Orderitems::get_comment_list(['teacher_id' => $teacher_id]);
            $this->assign('comment_list', $comment_list);
            return $this->fetch('get_comment_list');
        }

        $this->assign('teacher_info', $teacher);
        $location = Location::find($teacher['location']);
        $this->assign('location_teacher', $location);
        $location = Country::find($teacher['country_id']);
        $this->assign('country_teacher', $location);

//        $date = time_to_date(time(), $location_login, 'Y-m-d H:i:s');
//        echo $date;
        $date = time_to_date(time(), $location_login, 'Y-m-d');
        $dates = explode('-', $date);
        $this->assign('dates', $dates);

        $daytimes = Daytime::get_day_30($teacher_id, $location, $location_login, $this->user_id);
        $this->assign('daytimes', json_encode($daytimes));

        $cnt = Orderitems::alias('c')->field('c.*, location_name,t.ico_file,username,country_name')
            ->join('cms_users u', 'user_id = u.id')
            ->join('cms_location l', 'location = l.id', 'left')
            ->join('cms_country t', 'country_id = t.id', 'left')
            ->where(['teacher_id' => $teacher_id])->where('comment_student_time', 'gt', 0)->count();
        $this->assign('cnt', $cnt);

        $comment_list = Orderitems::get_comment_list(['teacher_id' => $teacher_id]);
        $this->assign('comment_list', $comment_list);

        $date2 = time_to_date(time(), get_user_timezone(), 'Y-m-d H:i:s');
        $time2 = strtotime($date2);
        $this->assign('time_now', $time2);
        $this->assign('date_now', $date2);

        return $this->fetch();
    }

    public function get_comment_list($teacher_id)
    {
        $location_login = get_user_timezone();
        $this->assign('location_login', $location_login);

        $comment_list = Orderitems::get_comment_list(['teacher_id' => $teacher_id]);
        $this->assign('comment_list', $comment_list);
        return $this->fetch();
    }

    //获取一周设置了上课的时间
    public function get_times($teacher_id = 0, $date = '')
    {
        if (!$teacher_id || !$date) {
            $ret = ['code' => 201];
        } else {
            $times = Daytime::get_week_times($teacher_id, $date, get_user_timezone());
            $ret = ['code' => 200, 'data'=>$times];
        }
        echo json_encode($ret);
    }

    //确认下单
    public function confirm()
    {
        $teacher_id = input('teacher_id');
        if (!$this->user_id) {
            $url = url_base64_encode(url('detail', ['teacher_id' => $teacher_id]));
            $this->redirect('sign/learner', ['continue'=>$url]);
        }
        $times = input('times');
        $user = Users::find($this->user_id);
        $teacher = Users::where(['id' => $teacher_id, 'status' => 1, 'close_state' => 0])->find();
        if (!$teacher_id) {
            $this->redirect('/');
        }
        if (!$times) {
            $this->redirect('/');
        }
        $location_login = get_user_timezone();
        $weekauto = input('weekauto', 0);
        $result = Daytime::get_cart($times, $teacher, $user, $location_login, $weekauto);
        if ($result['code']!=200) {
            $this->error($result['msg']);
        }
//        print_r($result);print_r(input('post.'));
        $dayids = $result['dayids'];
        $dates = $result['dates'];
        $times = $result['times'];
        if ($result['code'] == 201) {
            $this->error($result['msg']);
        }
        $cnt = count($dayids);
        $this->assign('cnt', $cnt);
        $this->assign('money', $result['money']);
        $this->assign('invitation_money', $result['invitation_money']);
        $this->assign('invitation_money_use', $result['invitation_money_use']);
        $this->assign('use_money', $result['use_money']);
        $this->assign('pay_money', $result['pay_money']);
        $this->assign('dayids', $dayids);
        $this->assign('dates', $dates);
        $this->assign('times', $times);
        $this->assign('user_info', $user);
        $this->assign('teacher', $teacher);
        $this->assign('teacher_id', $teacher_id);
        $this->assign('daytimes', $result['datas']);

        $device_type = get_device_type();
        $is_wechat_browser = 1;
        if ($device_type > 1) {
            if (!is_wechat_browser()) {
                $is_wechat_browser = 0;
            }
        }
        $this->assign('is_wechat_browser', $is_wechat_browser);

        return $this->fetch();
    }

    public function booked()
    {
        //预约下单
        if ($this->request->isAjax()) {
            $data = input('post.');
            $ret = Order::create_order($data, $this->user_id);
        } else {
            $ret = ['code' => '201', 'msg' => 'Illegal request'];
        }
        echo json_encode($ret);
    }

    //支付成功
    public function succeed($order_id = 0)
    {
        $order = Order::where('id|order_sn', $order_id)->find();
        if (!$order) {
            $this->redirect('/');
        }
        if (!$order['pay_time']) {
            $this->redirect('payment/payagain', ['order_id'=>$order_id]);
        }
        $this->assign('order', $order);
        $teacher = Users::find($order['teacher_id']);
        $this->assign('teacher', $teacher);

        $list = Orderitems::where('order_id', $order['id'])->select();
        $this->assign('lists', $list);

        return $this->fetch();
    }

}