<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2021/5/10
 * Time: 23:24
 */

namespace app\api\home;

use app\api\model\Orderitems;
use app\api\model\Users;

class Member extends Base
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $user = $this->check_token();
        $this->user = $user;
    }

    public function logout()
    {
        Users::where('id', $this->user['id'])->setField('push_id', null);
        $ret = ['code' => 200, 'msg' => 'Success'];
        $this->returnJson($ret);
    }

    //设置极光id
    public function set_push_id()
    {
        $push_id = str_replace('null', '', input('push_id'));
        if ($push_id) {
            Users::where('id', $this->user['id'])->setField('push_id', $push_id);
            $ret = ['code' => 200, 'msg' => 'Success'];
        } else {
            $ret = ['code' => 200, 'msg' => 'Success'];
//            $ret = ['code' => 201, 'msg' => 'id error'];
        }
        $this->returnJson($ret);
    }

    //个人信息
    public function get_profile()
    {
        $ret = ['code'=>200, 'data'=>$this->user, 'msg' => 'success'];
        $this->returnJson($ret);
    }

    /**
     * 课程列表
     * type：1今天待上课，2将要上课的，3已完成的
     */
    public function get_class_list()
    {
        $type = input('type', 1);
        list($list, $count) = Orderitems::get_list($this->user, $type);
        $ret = ['code'=>200, 'data' => ['list' => $list, 'count' => $count, 'now_time' => time()] ];
        $this->returnJson($ret);
    }

    //评价课程
    public function comment_class()
    {
        $score = input('score');
        $comment = input('comment');
        $class_id = input('class_id');
        $ret = Orderitems::to_comment($class_id, $score, $comment, $this->user);
        $this->returnJson($ret);
    }

    //获取单个课程，进入房间
    public function get_class_one($id = 0)
    {
        $ret = Orderitems::get_one($this->user, $id);
        $this->returnJson($ret);
    }

    //进入房间
    public function in_room($classin_id = 0)
    {
        $ret = Orderitems::in_room($this->user, $classin_id);
        $this->returnJson($ret);
    }

    //退出房间
    public function out_room($classin_id = 0, $act = 0)
    {
        $ret = Orderitems::out_room($this->user, $classin_id, $act);
        $this->returnJson($ret);
    }

    //开始上课
    public function class_begin($classin_id = 0)
    {
        $ret = Orderitems::class_begin($classin_id, $this->user);
        $this->returnJson($ret);
    }

}
